displayName=WhosGrindingClanPanel
author=Oyama
support=https://github.com/ItMeansBigMountain/WhosGrindingClanPanel
description=WhosGrindingClanPanel RuneLite plugin.
tags=whosgrindingclanpanel,runelite,osrs
plugins=com.itmeansbigmountain.whosgrindingclanpanel.WhosGrindingClanPanelPlugin
